#include <stdlib.h>
#include <iostream>
#include <fstream>
#include <math.h>
#include <cmath>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/time.h>
#include <sys/timeb.h>
#include <string.h>
#include <string>
#include <string.h>
#include <unistd.h>
#include <stdio.h>
#include <sstream>
#include <wordexp.h>
#include <fcntl.h>
#include <errno.h>
#include <omp.h>
#include <sys/shm.h>
#include <signal.h>
#include <iomanip>
#include <ctime>
#include <sched.h>